// minimap.sc — a live minimap in the top-left corner for everyone, no client mods (only a server resource pack).
// Needs the server resource pack from resourcepacks/minimap/ (font pinkgolem:mm + core/text.vsh +
// invisible white bossbar). Each player gets a WHITE bossbar whose title IS the map: 24x24 cells (4x4 blocks each,
// round mask) coloured from the vanilla map colours of the top block (map_colour) with map-style height shading,
// friends as coloured dots (clamped to the rim when far), you as a gold arrow in the middle, a pink ring and an N.
// Every colour carries a marker in its low bits (R&3 = 1, G&3 = 2, B&3 = 3 cells / 1 overlays) that the pack's shader
// uses to move exactly these glyphs from the centred title to the corner. Generated by resourcepacks/minimap/build_app.py — edit that.
// /minimap (toggle), /minimap on|off. Colours are cached per cell (30 s) so an update is ~1000 map lookups.

__config() -> {'stay_loaded' -> true, 'scope' -> 'global', 'commands' -> {'' -> 'toggle', 'on' -> ['set_on', true], 'off' -> ['set_on', false]}};

global_N = 24; global_MID = 12; global_TOP = 10; global_S = 4; global_EVERY = 4; global_TTL = 600;
global_neg = ['', '', '', '', '', '', '', ''];
global_pos = ['', '', '', '', '', '', '', ''];
global_row = ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''];
global_dot = ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''];
global_arr = ['', '', '', '', '', '', '', ''];
global_frame = ''; global_north = '';
global_nb = ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''];
global_col = {'grass' -> 8368696, 'sand' -> 16247203, 'wool' -> 13092807, 'tnt' -> 16711680, 'ice' -> 10526975, 'iron' -> 10987431, 'foliage' -> 31744, 'snow' -> 16777215, 'clay' -> 10791096, 'dirt' -> 9923917, 'stone' -> 7368816, 'water' -> 4210943, 'wood' -> 9402184, 'quartz' -> 16776437, 'adobe' -> 14188339, 'magenta' -> 11685080, 'light_blue' -> 6724056, 'yellow' -> 15066419, 'lime' -> 8375321, 'pink' -> 15892389, 'gray' -> 5000268, 'light_gray' -> 10066329, 'cyan' -> 5013401, 'purple' -> 8339378, 'blue' -> 3361970, 'brown' -> 6704179, 'green' -> 6717235, 'red' -> 10040115, 'black' -> 1644825, 'gold' -> 16445005, 'diamond' -> 6085589, 'lapis' -> 4882687, 'emerald' -> 55610, 'obsidian' -> 8476209, 'netherrack' -> 7340544, 'white_terracotta' -> 13742497, 'orange_terracotta' -> 10441252, 'magenta_terracotta' -> 9787244, 'light_blue_terracotta' -> 7367818, 'yellow_terracotta' -> 12223780, 'lime_terracotta' -> 6780213, 'pink_terracotta' -> 10505550, 'gray_terracotta' -> 3746083, 'light_gray_terracotta' -> 8874850, 'cyan_terracotta' -> 5725276, 'purple_terracotta' -> 8014168, 'blue_terracotta' -> 4996700, 'brown_terracotta' -> 4993571, 'green_terracotta' -> 5001770, 'red_terracotta' -> 9321518, 'black_terracotta' -> 2430480, 'crimson_nylium' -> 12398641, 'crimson_stem' -> 9715553, 'crimson_hyphae' -> 6035741, 'warped_nylium' -> 1474182, 'warped_stem' -> 3837580, 'warped_hyphae' -> 5647422, 'warped_wart' -> 1356933, 'deepslate' -> 6579300, 'raw_iron' -> 14200723, 'glow_lichen' -> 8365974};
global_fcols = [16733525, 5636095, 16777045, 5635925, 16733695, 16755200, 11141375, 43775];
global_cache = {};
global_pref = {};           // name -> true/false (/minimap on|off); unset = global_DEFAULT
global_DEFAULT = false;     // true once the server resource pack is live (server.properties resource-pack)
global_bars = {};
global_base = {};
global_last = {};

__on_start() -> (o = read_file('prefs', 'json'); if (o, global_pref = o); d = read_file('default', 'json'); if (d != null, global_DEFAULT = d));

_shown(n) -> (v = global_pref:n; if (v == null, global_DEFAULT, v));
toggle() -> (p = player(); set_on(!_shown(p ~ 'name')));
set_on(v) -> (
  p = player(); n = p ~ 'name';
  global_pref:n = v; if (!v, _drop(n));
  write_file('prefs', 'json', global_pref);
  if (v, 'minimap on', 'minimap off — /minimap on to bring it back')
);
// admin: script in minimap run set_default(true)  (after the resource pack is set in server.properties)
set_default(v) -> (global_DEFAULT = v; write_file('default', 'json', v); if (!v, for (keys(global_bars), if (!_shown(_), _drop(_)))); str('default %s', v));

_id(n) -> 'mm:' + lower(n);
_drop(n) -> (delete(global_last, n); if (has(global_bars, n), run(str('bossbar remove %s', _id(n))); delete(global_bars, n)));
_ensure(n) -> (
  if (has(global_bars, n), return());
  id = _id(n);
  run(str('bossbar add %s ""', id)); run(str('bossbar set %s color white', id));
  run(str('bossbar set %s max 1', id)); run(str('bossbar set %s value 0', id)); run(str('bossbar set %s players %s', id, n));
  global_bars:n = true
);

__on_player_disconnects(p, r) -> (n = p ~ 'name'; _drop(n); delete(global_last, n); delete(global_base, n));

// spaces of any width from the power-of-two space glyphs
_sp(k) -> (
  s = ''; l = if (k < 0, global_neg, global_pos); k = abs(k);
  for (range(8), if (bitwise_and(k, bitwise_shift_left(1, _)) != 0, s += l:_));
  s
);

_mark(rgb, cell) -> (
  r = bitwise_or(bitwise_and(floor(rgb / 65536) % 256, 252), 1);
  g = bitwise_or(bitwise_and(floor(rgb / 256) % 256, 252), 2);
  b = bitwise_or(bitwise_and(rgb % 256, 252), if (cell, 3, 1));
  str('#%02X%02X%02X', r, g, b)
);

// one sample on the 2-block grid: [marked colour, height, time], cached
_cell(cx, cz, t) -> (
  k = cx * 100003 + cz;
  c = global_cache:k;
  if (c && t - c:2 < global_TTL, return(c));
  x = cx * 2; z = cz * 2;
  y = top('surface', [x, 0, z]) - 1;
  b = block(x, y, z); nm = map_colour(b);
  while (nm == 'air' && y > -64, 8, y += -1; b = block(x, y, z); nm = map_colour(b));
  rgb = global_col:nm; if (rgb == null, rgb = 7368816);
  if (nm == 'water',
    d = 0; while (d < 6 && map_colour(block(x, y - d - 1, z)) == 'water', 6, d += 1);
    rgb = _scale(rgb, 1.05 - d * 0.07),
    yn = top('surface', [x, 0, z - 2]) - 1;                  // map-style shading against the cell to the north
    rgb = _scale(rgb, if (y > yn, 1.0, y < yn, 0.706, 0.863)));
  c = [_mark(rgb, true), y, t];
  global_cache:k = c;
  c
);

_scale(rgb, f) -> (
  r = min(255, floor(floor(rgb / 65536) % 256 * f)); g = min(255, floor(floor(rgb / 256) % 256 * f)); b = min(255, floor(rgb % 256 * f));
  r * 65536 + g * 256 + b
);

__on_tick() -> (
  t = tick_time();
  if (t % 200 == 0 && length(global_cache) > 60000, global_cache = {});
  for (player('all'),
    p = _; n = p ~ 'name';
    if ((p ~ 'player_type') == 'fake' || !_shown(n), continue());
    if ((t + hash_code(n)) % global_EVERY != 0, continue());
    _ensure(n);
    if ((p ~ 'dimension') != 'overworld', run(str('bossbar set %s name ""', _id(n))); continue());
    _render(p, n, t)
  )
);

// the map turns with you: "up" is where you look (yaw quantised to 6°)
_render(p, n, t) -> (
  q = pos(p); yw = round(query(p, 'yaw') / 6) * 6;
  key = [floor(q:0 / 2), floor(q:2 / 2), yw];
  b = global_base:n;
  if (b && b:0 == key && t - b:1 < 100, parts = copy(b:2), parts = _terrain(q, yw, t); global_base:n = [key, t, copy(parts)]);
  _overlays(p, n, q, yw, parts)
);

_terrain(q, yw, t) -> (
  M = global_MID; R2 = (M + 0.5) * (M + 0.5); S = global_S;
  fx = -sin(yw); fz = cos(yw); rx = -cos(yw); rz = -sin(yw);          // forward / right in the world
  parts = []; cur = ''; curc = null; budget = 90;
  for (range(global_N),
    row = _; ch = global_row:row; dy = row - M + 0.5;
    for (range(global_N),
      dx = _ - M + 0.5;
      if (dx * dx + dy * dy > R2,
        cur += global_pos:1,                                          // +2 px, no cell
        wx = q:0 + (dx * rx - dy * fx) * S; wz = q:2 + (dx * rz - dy * fz) * S;
        cx = floor(wx / 2); cz = floor(wz / 2);
        c = global_cache:(cx * 100003 + cz);
        if (!c || (t - c:2 >= global_TTL && budget > 0), c = _cell(cx, cz, t); budget += -1);
        col = c:0;
        if (col != curc, if (cur != '', parts += {'text' -> cur, 'color' -> if (curc, curc, '#FDFEFD')}); cur = ''; curc = col);
        cur += ch
      )
    );
    cur += _sp(-2 * global_N)                                         // back to the row start
  );
  if (cur != '', parts += {'text' -> cur, 'color' -> if (curc, curc, '#FDFEFD')});
  parts
);

_overlays(p, n, q, yw, parts) -> (
  M = global_MID; N = global_N; S = global_S;
  fx = -sin(yw); fz = cos(yw); rx = -cos(yw); rz = -sin(yw);
  // frame: cursor -4 → frame (advance 2N+9) → back to 0; the N badge rides the ring where north is
  nsx = sin(yw); nsy = cos(yw); rr = M * 2 + 3;
  bx = round(N + nsx * rr - 4); btop = round(global_TOP + N + nsy * rr - 4);
  parts += {'text' -> _sp(-4) + global_frame + _sp(-(2 * N + 5)) + _sp(bx) + global_nb:(btop - global_TOP + 7) + _sp(-(bx + 9)), 'color' -> '#FDFEFD'};
  // friends
  i = 0;
  for (player('all'),
    o = _; on = o ~ 'name';
    if (on == n || (o ~ 'dimension') != (p ~ 'dimension') || (o ~ 'player_type') == 'fake', continue());
    oq = pos(o); ox = oq:0 - q:0; oz = oq:2 - q:2;
    sx = (ox * rx + oz * rz) / S; sy = -(ox * fx + oz * fz) / S;         // on screen: right, down
    d = sqrt(sx * sx + sy * sy); if (d > M - 1.5, sx = sx / d * (M - 1.5); sy = sy / d * (M - 1.5));
    cx = round(M + sx - 0.5); cz = max(0, min(N - 1, round(M + sy - 0.5)));
    px = cx * 2 - 1;
    parts += {'text' -> _sp(px) + global_dot:cz + _sp(-(px + 5)), 'color' -> _mark(global_fcols:(hash_code(on) % 8), false)};
    i += 1
  );
  // you: a gold arrow pointing where you look (north up)
  parts += {'text' -> _sp(M * 2 - 3) + global_arr:0 + _sp(-(M * 2 - 3 + 8)) + _sp(global_N * 2), 'color' -> '#FDDA21'};
  root = encode_json({'text' -> '', 'font' -> 'pinkgolem:mm', 'shadow_color' -> 0, 'extra' -> parts});
  if (global_last:n != root, global_last:n = root; run(str('bossbar set %s name %s', _id(n), root)))   // unchanged = nothing sent
);
