"""build_app.py — writes scarpet-apps/minimap.sc (the server side of the minimap; the pack: build_pack.py).
The font's private-use characters are embedded here so the .sc file carries them literally.
"""
import os

CELLS = 24
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "scarpet-apps", "minimap.sc")
NEG = [chr(0xF801 + i) for i in range(8)]     # -1 -2 -4 ... -128
POS = [chr(0xF811 + i) for i in range(8)]     # +1 +2 +4 ... +128
ROW = [chr(0xE000 + r) for r in range(CELLS)]
DOT = [chr(0xE100 + r) for r in range(CELLS)]
ARR = [chr(0xE200 + d) for d in range(8)]
FRAME, NORTH = chr(0xE300), chr(0xE301)
NB = [chr(0xE400 + i) for i in range(2 * CELLS + 7)]


def sl(l):
    return "[" + ", ".join("'" + c + "'" for c in l) + "]"


# vanilla MapColor RGB by carpet's map_colour() names
COLORS = {
    "grass": 0x7FB238, "sand": 0xF7E9A3, "wool": 0xC7C7C7, "tnt": 0xFF0000, "ice": 0xA0A0FF, "iron": 0xA7A7A7, "foliage": 0x007C00,
    "snow": 0xFFFFFF, "clay": 0xA4A8B8, "dirt": 0x976D4D, "stone": 0x707070, "water": 0x4040FF, "wood": 0x8F7748, "quartz": 0xFFFCF5,
    "adobe": 0xD87F33, "magenta": 0xB24CD8, "light_blue": 0x6699D8, "yellow": 0xE5E533, "lime": 0x7FCC19, "pink": 0xF27FA5,
    "gray": 0x4C4C4C, "light_gray": 0x999999, "cyan": 0x4C7F99, "purple": 0x7F3FB2, "blue": 0x334CB2, "brown": 0x664C33,
    "green": 0x667F33, "red": 0x993333, "black": 0x191919, "gold": 0xFAEE4D, "diamond": 0x5CDBD5, "lapis": 0x4A80FF,
    "emerald": 0x00D93A, "obsidian": 0x815631, "netherrack": 0x700200, "white_terracotta": 0xD1B1A1, "orange_terracotta": 0x9F5224,
    "magenta_terracotta": 0x95576C, "light_blue_terracotta": 0x706C8A, "yellow_terracotta": 0xBA8524, "lime_terracotta": 0x677535,
    "pink_terracotta": 0xA04D4E, "gray_terracotta": 0x392923, "light_gray_terracotta": 0x876B62, "cyan_terracotta": 0x575C5C,
    "purple_terracotta": 0x7A4958, "blue_terracotta": 0x4C3E5C, "brown_terracotta": 0x4C3223, "green_terracotta": 0x4C522A,
    "red_terracotta": 0x8E3C2E, "black_terracotta": 0x251610, "crimson_nylium": 0xBD3031, "crimson_stem": 0x943F61,
    "crimson_hyphae": 0x5C191D, "warped_nylium": 0x167E86, "warped_stem": 0x3A8E8C, "warped_hyphae": 0x562C3E,
    "warped_wart": 0x14B485, "deepslate": 0x646464, "raw_iron": 0xD8AF93, "glow_lichen": 0x7FA796,
}
cmap = "{" + ", ".join(f"'{k}' -> {v}" for k, v in COLORS.items()) + "}"

SRC = r"""// minimap.sc — a live minimap in the top-left corner for everyone, no client mods (only a server resource pack).
// Needs the server resource pack from resourcepacks/minimap/ (font clawdblock:mm + core/text.vsh +
// invisible white bossbar). Each player gets a WHITE bossbar whose title IS the map: 24x24 cells (4x4 blocks each,
// round mask) coloured from the vanilla map colours of the top block (map_colour) with map-style height shading,
// friends as coloured dots (clamped to the rim when far), you as a gold arrow in the middle, a pink ring and an N.
// Every colour carries a marker in its low bits (R&3 = 1, G&3 = 2, B&3 = 3 cells / 1 overlays) that the pack's shader
// uses to move exactly these glyphs from the centred title to the corner. Generated by resourcepacks/minimap/build_app.py — edit that.
// /minimap (toggle), /minimap on|off. Colours are cached per cell (30 s) so an update is ~1000 map lookups.

__config() -> {'stay_loaded' -> true, 'scope' -> 'global', 'commands' -> {'' -> 'toggle', 'on' -> ['set_on', true], 'off' -> ['set_on', false]}};

global_N = %CELLS%; global_MID = %MID%; global_TOP = 10; global_S = 4; global_EVERY = 4; global_TTL = 600;
global_neg = %NEG%;
global_pos = %POS%;
global_row = %ROW%;
global_dot = %DOT%;
global_arr = %ARR%;
global_frame = '%FRAME%'; global_north = '%NORTH%';
global_nb = %NB%;
global_col = %CMAP%;
global_fcols = [16733525, 5636095, 16777045, 5635925, 16733695, 16755200, 11141375, 43775];
global_cache = {};
global_pref = {};           // name -> true/false (/minimap on|off); unset = global_DEFAULT
global_DEFAULT = false;     // true once the server resource pack is live (server.properties resource-pack)
global_bars = {};
global_base = {};
global_last = {};

__on_start() -> (o = read_file('prefs', 'json'); if (o, global_pref = o); d = read_file('default', 'json'); if (d != null, global_DEFAULT = d));

_shown(n) -> (v = global_pref:n; if (v == null, global_DEFAULT, v));
toggle() -> (p = player(); set_on(!_shown(p ~ 'name')));
set_on(v) -> (
  p = player(); n = p ~ 'name';
  global_pref:n = v; if (!v, _drop(n));
  write_file('prefs', 'json', global_pref);
  if (v, 'minimap on', 'minimap off — /minimap on to bring it back')
);
// admin: script in minimap run set_default(true)  (after the resource pack is set in server.properties)
set_default(v) -> (global_DEFAULT = v; write_file('default', 'json', v); if (!v, for (keys(global_bars), if (!_shown(_), _drop(_)))); str('default %s', v));

_id(n) -> 'mm:' + lower(n);
_drop(n) -> (delete(global_last, n); if (has(global_bars, n), run(str('bossbar remove %s', _id(n))); delete(global_bars, n)));
_ensure(n) -> (
  if (has(global_bars, n), return());
  id = _id(n);
  run(str('bossbar add %s ""', id)); run(str('bossbar set %s color white', id));
  run(str('bossbar set %s max 1', id)); run(str('bossbar set %s value 0', id)); run(str('bossbar set %s players %s', id, n));
  global_bars:n = true
);

__on_player_disconnects(p, r) -> (n = p ~ 'name'; _drop(n); delete(global_last, n); delete(global_base, n));

// spaces of any width from the power-of-two space glyphs
_sp(k) -> (
  s = ''; l = if (k < 0, global_neg, global_pos); k = abs(k);
  for (range(8), if (bitwise_and(k, bitwise_shift_left(1, _)) != 0, s += l:_));
  s
);

_mark(rgb, cell) -> (
  r = bitwise_or(bitwise_and(floor(rgb / 65536) % 256, 252), 1);
  g = bitwise_or(bitwise_and(floor(rgb / 256) % 256, 252), 2);
  b = bitwise_or(bitwise_and(rgb % 256, 252), if (cell, 3, 1));
  str('#%02X%02X%02X', r, g, b)
);

// one sample on the 2-block grid: [marked colour, height, time], cached
_cell(cx, cz, t) -> (
  k = cx * 100003 + cz;
  c = global_cache:k;
  if (c && t - c:2 < global_TTL, return(c));
  x = cx * 2; z = cz * 2;
  y = top('surface', [x, 0, z]) - 1;
  b = block(x, y, z); nm = map_colour(b);
  while (nm == 'air' && y > -64, 8, y += -1; b = block(x, y, z); nm = map_colour(b));
  rgb = global_col:nm; if (rgb == null, rgb = 7368816);
  if (nm == 'water',
    d = 0; while (d < 6 && map_colour(block(x, y - d - 1, z)) == 'water', 6, d += 1);
    rgb = _scale(rgb, 1.05 - d * 0.07),
    yn = top('surface', [x, 0, z - 2]) - 1;                  // map-style shading against the cell to the north
    rgb = _scale(rgb, if (y > yn, 1.0, y < yn, 0.706, 0.863)));
  c = [_mark(rgb, true), y, t];
  global_cache:k = c;
  c
);

_scale(rgb, f) -> (
  r = min(255, floor(floor(rgb / 65536) % 256 * f)); g = min(255, floor(floor(rgb / 256) % 256 * f)); b = min(255, floor(rgb % 256 * f));
  r * 65536 + g * 256 + b
);

__on_tick() -> (
  t = tick_time();
  if (t % 200 == 0 && length(global_cache) > 60000, global_cache = {});
  for (player('all'),
    p = _; n = p ~ 'name';
    if ((p ~ 'player_type') == 'fake' || !_shown(n), continue());
    if ((t + hash_code(n)) % global_EVERY != 0, continue());
    _ensure(n);
    if ((p ~ 'dimension') != 'overworld', run(str('bossbar set %s name ""', _id(n))); continue());
    _render(p, n, t)
  )
);

// the map turns with you: "up" is where you look (yaw quantised to 6°)
_render(p, n, t) -> (
  q = pos(p); yw = round(query(p, 'yaw') / 6) * 6;
  key = [floor(q:0 / 2), floor(q:2 / 2), yw];
  b = global_base:n;
  if (b && b:0 == key && t - b:1 < 100, parts = copy(b:2), parts = _terrain(q, yw, t); global_base:n = [key, t, copy(parts)]);
  _overlays(p, n, q, yw, parts)
);

_terrain(q, yw, t) -> (
  M = global_MID; R2 = (M + 0.5) * (M + 0.5); S = global_S;
  fx = -sin(yw); fz = cos(yw); rx = -cos(yw); rz = -sin(yw);          // forward / right in the world
  parts = []; cur = ''; curc = null; budget = 90;
  for (range(global_N),
    row = _; ch = global_row:row; dy = row - M + 0.5;
    for (range(global_N),
      dx = _ - M + 0.5;
      if (dx * dx + dy * dy > R2,
        cur += global_pos:1,                                          // +2 px, no cell
        wx = q:0 + (dx * rx - dy * fx) * S; wz = q:2 + (dx * rz - dy * fz) * S;
        cx = floor(wx / 2); cz = floor(wz / 2);
        c = global_cache:(cx * 100003 + cz);
        if (!c || (t - c:2 >= global_TTL && budget > 0), c = _cell(cx, cz, t); budget += -1);
        col = c:0;
        if (col != curc, if (cur != '', parts += {'text' -> cur, 'color' -> if (curc, curc, '#FDFEFD')}); cur = ''; curc = col);
        cur += ch
      )
    );
    cur += _sp(-2 * global_N)                                         // back to the row start
  );
  if (cur != '', parts += {'text' -> cur, 'color' -> if (curc, curc, '#FDFEFD')});
  parts
);

_overlays(p, n, q, yw, parts) -> (
  M = global_MID; N = global_N; S = global_S;
  fx = -sin(yw); fz = cos(yw); rx = -cos(yw); rz = -sin(yw);
  // frame: cursor -4 → frame (advance 2N+9) → back to 0; the N badge rides the ring where north is
  nsx = sin(yw); nsy = cos(yw); rr = M * 2 + 3;
  bx = round(N + nsx * rr - 4); btop = round(global_TOP + N + nsy * rr - 4);
  parts += {'text' -> _sp(-4) + global_frame + _sp(-(2 * N + 5)) + _sp(bx) + global_nb:(btop - global_TOP + 7) + _sp(-(bx + 9)), 'color' -> '#FDFEFD'};
  // friends
  i = 0;
  for (player('all'),
    o = _; on = o ~ 'name';
    if (on == n || (o ~ 'dimension') != (p ~ 'dimension') || (o ~ 'player_type') == 'fake', continue());
    oq = pos(o); ox = oq:0 - q:0; oz = oq:2 - q:2;
    sx = (ox * rx + oz * rz) / S; sy = -(ox * fx + oz * fz) / S;         // on screen: right, down
    d = sqrt(sx * sx + sy * sy); if (d > M - 1.5, sx = sx / d * (M - 1.5); sy = sy / d * (M - 1.5));
    cx = round(M + sx - 0.5); cz = max(0, min(N - 1, round(M + sy - 0.5)));
    px = cx * 2 - 1;
    parts += {'text' -> _sp(px) + global_dot:cz + _sp(-(px + 5)), 'color' -> _mark(global_fcols:(hash_code(on) % 8), false)};
    i += 1
  );
  // you: a gold arrow pointing where you look (north up)
  parts += {'text' -> _sp(M * 2 - 3) + global_arr:0 + _sp(-(M * 2 - 3 + 8)) + _sp(global_N * 2), 'color' -> '#FDDA21'};
  root = encode_json({'text' -> '', 'font' -> 'clawdblock:mm', 'shadow_color' -> 0, 'extra' -> parts});
  if (global_last:n != root, global_last:n = root; run(str('bossbar set %s name %s', _id(n), root)))   // unchanged = nothing sent
);
"""

src = (SRC.replace("%CELLS%", str(CELLS)).replace("%MID%", str(CELLS // 2)).replace("%NEG%", sl(NEG)).replace("%POS%", sl(POS))
       .replace("%ROW%", sl(ROW)).replace("%DOT%", sl(DOT)).replace("%ARR%", sl(ARR)).replace("%FRAME%", FRAME)
       .replace("%NORTH%", NORTH).replace("%NB%", sl(NB)).replace("%CMAP%", cmap))
open(OUT, "w", encoding="utf-8").write(src)
print(OUT, len(src))
